# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 500)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.radio_add = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_add.setGeometry(QtCore.QRect(120, 90, 100, 20))
        self.radio_add.setObjectName("radio_add")
        self.radio_sub = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_sub.setGeometry(QtCore.QRect(240, 90, 100, 20))
        self.radio_sub.setObjectName("radio_sub")
        self.radio_mul = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_mul.setGeometry(QtCore.QRect(360, 90, 100, 20))
        self.radio_mul.setObjectName("radio_mul")
        self.radio_div = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_div.setGeometry(QtCore.QRect(480, 90, 100, 20))
        self.radio_div.setObjectName("radio_div")
        self.line_entry = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.line_entry.setGeometry(QtCore.QRect(130, 160, 113, 21))
        self.line_entry.setObjectName("line_entry")
        self.button_enter = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_enter.setGeometry(QtCore.QRect(250, 155, 113, 32))
        self.button_enter.setObjectName("button_enter")
        self.button_calc = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_calc.setGeometry(QtCore.QRect(180, 220, 113, 32))
        self.button_calc.setObjectName("button_calc")
        self.radio_choose = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.radio_choose.setGeometry(QtCore.QRect(570, 90, 100, 20))
        self.radio_choose.setObjectName("radio_choose")
        self.list = QtWidgets.QListWidget(parent=self.centralwidget)
        self.list.setGeometry(QtCore.QRect(390, 130, 256, 192))
        self.list.setObjectName("list")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(290, 10, 231, 51))
        font = QtGui.QFont()
        font.setFamily("STIX Two Math")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.button_del = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_del.setEnabled(False)
        self.button_del.setGeometry(QtCore.QRect(450, 350, 113, 32))
        self.button_del.setObjectName("button_del")
        self.button_clear = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_clear.setGeometry(QtCore.QRect(180, 270, 113, 32))
        self.button_clear.setObjectName("button_clear")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 37))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.radio_add.setText(_translate("MainWindow", "Add"))
        self.radio_sub.setText(_translate("MainWindow", "Subtract"))
        self.radio_mul.setText(_translate("MainWindow", "Multiply "))
        self.radio_div.setText(_translate("MainWindow", "Divide"))
        self.button_enter.setText(_translate("MainWindow", "Enter"))
        self.button_calc.setText(_translate("MainWindow", "Calculate"))
        self.radio_choose.setText(_translate("MainWindow", "Choose"))
        self.button_del.setText(_translate("MainWindow", "Delete Entry"))
        self.button_clear.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
